language: erlang
branches:
  only:
    - master
notifications:
  email: chris@yunker.io
otp_release:
  - 17.3
  - 17.1
  - 17.0
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B03
  - R15B02
script:
  - make && make dialyzer && make test
